[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#FFD700"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#F0F0F0"
font = "sans serif"

[global]
showWarningOnDirectExecution = false
developmentMode = false
